/**
 * @page debug_guide VSCode Debugging Quick Guide
 * Being able to visualize how your code runs is a crucial step to resolving
 * issues in your programs, which otherwise could result in hours wasted
 * struggling to track down an obscure problem.
 * 
 * Set up properly, debugging C in VSCode will allow you to step through your
 * code and pause at designated points before continuing, or even go line by
 * line to give you a chance to observe how what you've written interacts with
 * inputs and variables.
 * 
 * @section flag The -g flag
 * To get started, we will want to add a new compiler flag to our default
 * <tt>-Wall -Wextra -Werror</tt> flags.  
 * The @p -g flag tells the compiler to preserve information that can be used
 * by our debugger to reference specific parts of the code, such as the names
 * of variables.
 * 
 * @section tasks VSCode Build Task
 * There are two primary ways to use this flag effeciently.  
 * You can either do it manually, such as typing out the entire command or
 * following your usual compile alias with it (in my case, <tt>fcc -g</tt>),
 * or you can create a task for VSCode to do it automatically when you try
 * to debug your project.
 * 
 * If you wish to use your existing setup, you can skip ahead to
 * @ref debugger "VSCode Debugging With LLDB".
 * 
 * To create a VSCode tasks file for the current project, press @p CMD +
 * @p SHIFT + @p P to open your command pallete.  
 * Type @p Tasks and select <tt>Tasks: Configure Default Build Task</tt>
 * from the list.
 * Type <tt>C/C++</tt> and select <tt>C/C++: clang build active file</tt>
 * 
 * This will automatically generate a file that looks something like this
 * 
 * @code{.c}
 * {
 * 	"tasks": [
 * 		{
 * 			"type": "cppbuild",
 * 			"label": "C/C++: clang build active file",
 * 			"command": "/usr/bin/clang",
 * 			"args": [
 * 				"-fcolor-diagnostics",
 * 				"-fansi-escape-codes",
 * 				"-g",
 * 				"${file}",
 * 				"-o",
 * 				"${fileDirname}/${fileBasenameNoExtension}"
 * 			],
 * 			"options": {
 * 				"cwd": "${fileDirname}"
 * 			},
 * 			"problemMatcher": [
 * 			"$gcc"
 * 			],
 * 			"group": {
 * 				"kind": "build",
 * 				"isDefault": true
 * 			},
 * 			"detail": "Task generated by Debugger."
 * 		}
 * 	],
 * 	"version": "2.0.0"
 * }
 * @endcode
 * 
 * @section debugger VSCode Debugging With LLDB
 * 
 */