name: Dispatch dependant repos to update

on: [push]

jobs:
  dispatch:
    strategy:
      matrix:
        repo: [
          "ft-spellbook/tgrekov-libft",
          "ft-spellbook/ft-spellbook",
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_PAT }}
          repository: ${{ matrix.repo }}
          event-type: global-update