name: Reusable workflow to generate Doxygen documentation and deploy to pages

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      brief:
        required: true
        type: string

jobs:
  docs:
    permissions:
      pages: write
      id-token: write
    environment:
      name: pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    env:
      DOXYGEN_PROJECT_NAME: ${{ inputs.name }}
      DOXYGEN_PROJECT_BRIEF: ${{ inputs.brief }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ts-graphviz/setup-graphviz@v1.2.0
      - uses: actions/checkout@v4
        with:
          repository: "ft-spellbook/doxygen-global"
          ref: master
          submodules: true
          path: "doxygen-global/"
      - uses: mattnotmitt/doxygen-action@1.9.5
        with:
          doxyfile-path: "doxygen-global/Doxyfile"
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "docs/html"
      - id: deploy-pages
        uses: actions/deploy-pages@v2
    